// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'dinotify', kind: "module", path: './dinotify.html', attributes: []},
{name: 'dinotify.Event', kind: "structdeclaration", path: './dinotify/Event.html', attributes: []},
{name: 'dinotify.iNotify', kind: "functiondeclaration", path: './dinotify/iNotify.html', attributes: ["auto"]},
{name: 'dinotify.INotifyTree', kind: "structdeclaration", path: './dinotify/INotifyTree.html', attributes: []},
{name: 'dinotify.INotifyTree.read', kind: "functiondeclaration", path: './dinotify/INotifyTree.read.html', attributes: []},
{name: 'dinotify.iNotifyTree', kind: "functiondeclaration", path: './dinotify/iNotifyTree.html', attributes: ["auto"]},
{name: 'dinotify.TreeEvent', kind: "structdeclaration", path: './dinotify/TreeEvent.html', attributes: []},
{name: 'dinotify.Watch', kind: "structdeclaration", path: './dinotify/Watch.html', attributes: []},
];
